[package]
name = "get_london_underground"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
reqwest = { version = "0.12.15", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0"